apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp
spec:
 type: NodePort
 ports:
   - port: 8888
     targetPort: 8888
     nodePort: 30001
 selector:
  app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rishald/myapp:20
        ports:
        - containerPort: 8888