apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rishald/myapp:21
        ports:
        - containerPort: 80